

on: [push]
jobs:
    # lint:
    #     needs: formatter
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #         - run: pip install flake8 && flake8 .
    test:
        # needs: lint
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - run: pip install -r requirements.txt
            - run: pytest
    formatter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install black && black ./src && black ./tests