on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install black && black .

            - run: pip install flake8 && flake8 ./src
    test:
        needs: sec_scan

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - run: pip install -r requirements.txt
            - run: pytest
    sec_scan:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install bandit && bandit -r ./src
